/** Real (room, stay_id) pairs sourced directly from github.com/SDP42/guestexperience's own
 * data/syntheticqrstayid.csv — the seed data that repo's own SQLite self-seeds from on first
 * boot (lib/db.ts), including on its deployed guestexperience.vercel.app instance. Fetched
 * once, on 2026-09-26, via that repo's raw GitHub content — not invented. Used to generate a
 * QR code that actually resolves to a real, personalised guest page when scanned against the
 * live deployment, since near_home_360 and guestexperience are two independently-deployed apps
 * with no shared database (see lib/integration/guestAppAdapter.ts's module comment for the
 * fuller explanation of why an HTTP bridge, not literal DB sharing, is what "connected" means
 * here). Both apps use the same Pillai_Hotel360 room-numbering scheme (floor 1-7, rooms 01-20),
 * so a near_home_360 room number maps directly onto a guestexperience one. */
export interface GuestExperienceStay {
  room: string;
  stayId: string;
  guestName: string;
  status: string;
}

export const GUEST_EXPERIENCE_STAYS: GuestExperienceStay[] = [
  { room: "101", stayId: "TPV4A", guestName: 'Shruti Joshi', status: "arriving" },
  { room: "102", stayId: "ER4PJ", guestName: 'Sofia Kowalski', status: "in_house" },
  { room: "103", stayId: "8Q595", guestName: 'Priya Kulkarni', status: "in_house" },
  { room: "104", stayId: "ABP6W", guestName: 'Emma Rossi', status: "arriving" },
  { room: "105", stayId: "485RS", guestName: 'James Silva', status: "in_house" },
  { room: "106", stayId: "2N6K8", guestName: 'Kavya Das', status: "in_house" },
  { room: "107", stayId: "4SY8B", guestName: 'Priya Gokhale', status: "arriving" },
  { room: "108", stayId: "H82QS", guestName: 'Noah Müller', status: "arriving" },
  { room: "109", stayId: "N9PF5", guestName: 'Lucas Wang', status: "in_house" },
  { room: "110", stayId: "9EKZ9", guestName: 'Chen Rossi', status: "arriving" },
  { room: "111", stayId: "HYNP3", guestName: 'Lucas Kowalski', status: "in_house" },
  { room: "112", stayId: "A3ATH", guestName: 'Meera Menon', status: "in_house" },
  { room: "113", stayId: "TFYSP", guestName: 'Gauri Mehta', status: "arriving" },
  { room: "114", stayId: "QRRJJ", guestName: 'Advait Joshi', status: "in_house" },
  { room: "115", stayId: "M2MHJ", guestName: 'Reyansh Deshpande', status: "arriving" },
  { room: "116", stayId: "85X68", guestName: 'Kavya Gupta', status: "in_house" },
  { room: "117", stayId: "RB698", guestName: 'Noah Silva', status: "arriving" },
  { room: "118", stayId: "WJM8G", guestName: 'Elena Tanaka', status: "in_house" },
  { room: "119", stayId: "5FTM3", guestName: 'Arjun Menon', status: "in_house" },
  { room: "120", stayId: "DVWSQ", guestName: 'Neha Pawar', status: "in_house" },
  { room: "201", stayId: "39759", guestName: 'Lucas Tanaka', status: "arriving" },
  { room: "202", stayId: "EWPBT", guestName: 'Kavya Gokhale', status: "in_house" },
  { room: "203", stayId: "SD3TK", guestName: 'Sofia Nguyen', status: "in_house" },
  { room: "204", stayId: "6J6WP", guestName: 'Sai Naik', status: "in_house" },
  { room: "205", stayId: "7SX78", guestName: 'Aditya Naik', status: "in_house" },
  { room: "206", stayId: "ETTA8", guestName: 'Pranav Menon', status: "in_house" },
  { room: "207", stayId: "7BCBJ", guestName: 'Liam Kowalski', status: "arriving" },
  { room: "208", stayId: "VKC2R", guestName: 'Emma Okafor', status: "arriving" },
  { room: "209", stayId: "8V5PB", guestName: 'Karan Deshpande', status: "in_house" },
  { room: "210", stayId: "44VDB", guestName: 'Mrunal Jadhav', status: "in_house" },
  { room: "211", stayId: "PKH8D", guestName: 'Emma Haddad', status: "in_house" },
  { room: "212", stayId: "FYPDK", guestName: 'Hana Nguyen', status: "in_house" },
  { room: "213", stayId: "22M62", guestName: 'Hana Kowalski', status: "in_house" },
  { room: "214", stayId: "D6GGW", guestName: 'Karan Joshi', status: "arriving" },
  { room: "215", stayId: "T8SSP", guestName: 'Aarav Gupta', status: "arriving" },
  { room: "216", stayId: "9D64H", guestName: 'Myra Patil', status: "in_house" },
  { room: "217", stayId: "9WJEA", guestName: 'Aniket Das', status: "arriving" },
  { room: "218", stayId: "ZSEY7", guestName: 'Sai Pillai', status: "in_house" },
  { room: "219", stayId: "J4DNJ", guestName: 'Noah Dubois', status: "in_house" },
  { room: "220", stayId: "D34KP", guestName: 'Fatima Rossi', status: "in_house" },
  { room: "301", stayId: "9SY5E", guestName: 'Gauri Shinde', status: "in_house" },
  { room: "302", stayId: "SS8GB", guestName: 'Priya Kulkarni', status: "in_house" },
  { room: "303", stayId: "2TFKZ", guestName: 'Liam Haddad', status: "in_house" },
  { room: "304", stayId: "8DXYY", guestName: 'Omar Haddad', status: "arriving" },
  { room: "305", stayId: "3XW54", guestName: 'Omar Dubois', status: "in_house" },
  { room: "306", stayId: "M8J8F", guestName: 'Kavya Iyer', status: "arriving" },
  { room: "307", stayId: "8EXDY", guestName: 'Yuki Wang', status: "arriving" },
  { room: "308", stayId: "5NK3R", guestName: 'Meera Fernandes', status: "arriving" },
  { room: "309", stayId: "P4JYK", guestName: 'Sneha Joshi', status: "in_house" },
  { room: "310", stayId: "V563Q", guestName: 'Chen Silva', status: "arriving" },
  { room: "311", stayId: "K7YZC", guestName: 'Fatima Tanaka', status: "arriving" },
  { room: "312", stayId: "FN3JM", guestName: 'Emma Wang', status: "in_house" },
  { room: "313", stayId: "5XFQA", guestName: 'Elena Kowalski', status: "in_house" },
  { room: "314", stayId: "JG6DQ", guestName: 'Elena Tanaka', status: "in_house" },
  { room: "315", stayId: "3NBJP", guestName: 'Om Sawant', status: "in_house" },
  { room: "316", stayId: "8VBV9", guestName: 'Yash Iyer', status: "arriving" },
  { room: "317", stayId: "CEDXJ", guestName: 'Vihaan Kapoor', status: "in_house" },
  { room: "318", stayId: "GKJQS", guestName: 'Diya Verma', status: "in_house" },
  { room: "319", stayId: "4PMZ7", guestName: 'Mateo García', status: "arriving" },
  { room: "320", stayId: "F6BWY", guestName: 'Reyansh Das', status: "in_house" },
  { room: "401", stayId: "5RQ5C", guestName: 'Emma Rossi', status: "arriving" },
  { room: "402", stayId: "9SZNM", guestName: 'Noah Rossi', status: "arriving" },
  { room: "403", stayId: "BY7G5", guestName: 'Omar Silva', status: "in_house" },
  { room: "404", stayId: "RQJRC", guestName: 'Kiara Agarwal', status: "in_house" },
  { room: "405", stayId: "J74DC", guestName: 'Chen García', status: "in_house" },
  { room: "406", stayId: "ARNWQ", guestName: 'Reyansh Rao', status: "in_house" },
  { room: "407", stayId: "FRJ62", guestName: 'Hana Dubois', status: "in_house" },
  { room: "408", stayId: "Y5ERF", guestName: 'Omar Nguyen', status: "in_house" },
  { room: "409", stayId: "H95NH", guestName: 'Meera Gokhale', status: "in_house" },
  { room: "410", stayId: "N74DH", guestName: 'Noah Kowalski', status: "arriving" },
  { room: "411", stayId: "47699", guestName: 'Chen Silva', status: "in_house" },
  { room: "412", stayId: "W9F4K", guestName: 'Rohan Fernandes', status: "in_house" },
  { room: "413", stayId: "HXQ32", guestName: 'James Kowalski', status: "in_house" },
  { room: "414", stayId: "BYC4F", guestName: 'Mia Smith', status: "in_house" },
  { room: "415", stayId: "T2YG2", guestName: 'Omar Kowalski', status: "in_house" },
  { room: "416", stayId: "SQDGQ", guestName: 'Tara Gokhale', status: "arriving" },
  { room: "417", stayId: "ZYTNT", guestName: 'Chen Kowalski', status: "arriving" },
  { room: "418", stayId: "P2MCD", guestName: 'Kabir Patil', status: "in_house" },
  { room: "419", stayId: "ZCPRH", guestName: 'Elena Tanaka', status: "arriving" },
  { room: "420", stayId: "BMEHA", guestName: 'Amara Kowalski', status: "arriving" },
  { room: "501", stayId: "2BXES", guestName: 'Mateo Silva', status: "in_house" },
  { room: "502", stayId: "TFHGV", guestName: 'Ishaan Patil', status: "in_house" },
  { room: "503", stayId: "FFTTM", guestName: 'Rohan Shah', status: "arriving" },
  { room: "504", stayId: "88MG3", guestName: 'Vihaan Gokhale', status: "arriving" },
  { room: "505", stayId: "CMCGJ", guestName: 'Mateo Okafor', status: "in_house" },
  { room: "506", stayId: "7F5WG", guestName: 'Myra Naik', status: "in_house" },
  { room: "507", stayId: "3CA67", guestName: 'Fatima Nguyen', status: "arriving" },
  { room: "508", stayId: "8CY8S", guestName: 'Yuki Tanaka', status: "in_house" },
  { room: "509", stayId: "3G3WE", guestName: 'Rahul Pawar', status: "in_house" },
  { room: "510", stayId: "4RDCW", guestName: 'Aditya Joshi', status: "in_house" },
  { room: "511", stayId: "MH4NF", guestName: 'James Wang', status: "in_house" },
  { room: "512", stayId: "6QTMC", guestName: 'Amara Müller', status: "in_house" },
  { room: "513", stayId: "YFTPF", guestName: 'Aarav Malhotra', status: "in_house" },
  { room: "514", stayId: "TV39V", guestName: 'James Silva', status: "in_house" },
  { room: "515", stayId: "MYV5H", guestName: 'Amara Smith', status: "in_house" },
  { room: "516", stayId: "VDTWM", guestName: 'Siddharth Mehta', status: "in_house" },
  { room: "517", stayId: "5G9NX", guestName: 'Mia Haddad', status: "arriving" },
  { room: "518", stayId: "83F48", guestName: 'Chen Kowalski', status: "in_house" },
  { room: "519", stayId: "MVH94", guestName: 'Neha Joshi', status: "arriving" },
  { room: "520", stayId: "MPJAC", guestName: 'Karan Rane', status: "in_house" },
  { room: "601", stayId: "QF5FF", guestName: 'Gauri Chavan', status: "in_house" },
  { room: "602", stayId: "JG7YG", guestName: 'Fatima Kowalski', status: "in_house" },
  { room: "603", stayId: "SXKJQ", guestName: 'Kiara Shinde', status: "in_house" },
  { room: "604", stayId: "XEKC7", guestName: 'Saanvi Banerjee', status: "arriving" },
  { room: "605", stayId: "M6FJD", guestName: 'Yuki García', status: "arriving" },
  { room: "606", stayId: "S3CBQ", guestName: 'Lucas Haddad', status: "in_house" },
  { room: "607", stayId: "2TT6F", guestName: 'Sofia Müller', status: "arriving" },
  { room: "608", stayId: "59P2Q", guestName: 'Amara Müller', status: "arriving" },
  { room: "609", stayId: "AGXMD", guestName: 'Sofia Müller', status: "in_house" },
  { room: "610", stayId: "FBCTE", guestName: 'Dev Rao', status: "in_house" },
  { room: "611", stayId: "FMPTB", guestName: 'Lucas Silva', status: "arriving" },
  { room: "612", stayId: "7VW3E", guestName: 'Karan Chavan', status: "arriving" },
  { room: "613", stayId: "EJ9EC", guestName: 'Advait Naik', status: "in_house" },
  { room: "614", stayId: "R5GEP", guestName: 'Pranav Fernandes', status: "arriving" },
  { room: "615", stayId: "25KW7", guestName: 'Aniket Rao', status: "arriving" },
  { room: "616", stayId: "S4FEC", guestName: 'Emma Müller', status: "in_house" },
  { room: "617", stayId: "PN2XX", guestName: 'Sai Shah', status: "arriving" },
  { room: "618", stayId: "N5D9Y", guestName: 'Noah Wang', status: "in_house" },
  { room: "619", stayId: "4WTZA", guestName: 'Sofia Silva', status: "in_house" },
  { room: "620", stayId: "2JJJD", guestName: 'James Tanaka', status: "in_house" },
  { room: "701", stayId: "MASS8", guestName: 'Liam Nguyen', status: "in_house" },
  { room: "702", stayId: "6QFE8", guestName: 'Mrunal Rao', status: "in_house" },
  { room: "703", stayId: "BJYJP", guestName: 'Amara Silva', status: "arriving" },
  { room: "704", stayId: "56656", guestName: 'Dev Das', status: "arriving" },
  { room: "705", stayId: "WF6ZA", guestName: 'Lucas Okafor', status: "arriving" },
  { room: "706", stayId: "S8MJK", guestName: 'Mia Silva', status: "in_house" },
  { room: "707", stayId: "WR34R", guestName: 'Priya Singh', status: "in_house" },
  { room: "708", stayId: "2DY4V", guestName: 'Diya Chavan', status: "in_house" },
  { room: "709", stayId: "XGZ9N", guestName: 'Tara Rane', status: "in_house" },
  { room: "710", stayId: "EQQ4T", guestName: 'Saanvi Rao', status: "arriving" },
];

const byRoom = new Map(GUEST_EXPERIENCE_STAYS.map((s) => [s.room, s]));

export function guestExperienceStayForRoom(room: string): GuestExperienceStay | null {
  return byRoom.get(room) ?? null;
}
